apiVersion: apps/v1
kind: Deployment
metadata:
  name: shyam-deployment
  namespace: data-import
  labels:
    app: shyam
spec:
  replicas: 5
  selector:
    matchLabels:
      app: shyam
  template:
    metadata:
      labels:
        app: shyam
    spec:
      containers:
      - name: shyam
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - shyamv1
          - weight: 50
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - local-server

---
apiVersion: v1
kind: Service
metadata:
  name: shyam-agentcis-svc
  namespace: data-import
  labels:
    app: shyam
    managed-by: shyam-chaudhary-team
spec:
  selector:
    app: shyam
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  ipFamilyPolicy: SingleStack
  ipFamilies: [IPv4]

---
# Horizontal Pod Autoscaler for shyam
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shyam-hpa
  namespace: data-import
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shyam-deployment
  minReplicas: 5
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
      - type: Pods
        value: 2
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
